name: Translate Repository to Thai

on:
  # Manually trigger the workflow
  workflow_dispatch:
  # Or schedule it (e.g., daily at midnight UTC)
  schedule:
    - cron: '0 0 * * *'

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          path: source-repo
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai>=1.0.0 pyyaml gitpython

      - name: Check out destination repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/ums-documentation-thai
          path: thai-repo
          token: ${{ secrets.DEST_REPO_PAT }}

      - name: Run translation script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Execute the translation script from the source repository
          python source-repo/.github/scripts/translate.py

      - name: Cleanup
        if: always()
        run: |
          rm -rf source-repo
          rm -rf thai-repo
